### ISSUE TITLE
恭喜，老师表扬你了

### ISSUE THREAD

**Issue by simplenty** [lirunjing-china/mylib#1]

**Comment by imofelrj** [comment]
.

**Comment by simplenty** [comment]
恭喜，我也听见表扬你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lirunjing-china/mylib"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月2日(星期天) 晚上7:45
收件人:&nbsp;"lirunjing-china/mylib"<mylib@noreply.github.com&gt;;
抄送:&nbsp;"空气"<lishangmingxuan@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lirunjing-china/mylib] 恭喜，老师表扬你了 (#1)





 
Closed #1.
